
x-airflow-common: &airflow-common
  build:
    context: .
    platforms:
      - linux/amd64
  image: mlops-airflow:latest
  platform: linux/amd64
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: 'ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg='
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    PYTHONPATH: /opt/airflow/scripts
  volumes:
    - ./dags:/opt/airflow/dags
    - ./scripts:/opt/airflow/scripts
    - ./data:/opt/airflow/data
    - ./reports:/opt/airflow/reports
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./gcp-key.json:/opt/airflow/gcp-key.json
  depends_on:
    postgres:
      condition: service_healthy
  networks:
    - mlops_net

services:
  postgres:
    image: postgres:13
    platform: linux/amd64
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    networks:
      - mlops_net

  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: airflow webserver
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: airflow scheduler
    restart: always

  tfvd:
    image: python:3.9-slim
    platform: linux/amd64
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: bash -lc "apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/* && pip install --no-cache-dir -r requirements-tfvd.txt && python -c \"import tensorflow_data_validation as tfdv; print('TFDV', tfdv.__version__)\""
    networks:
      - mlops_net

networks:
  mlops_net:
    driver: bridge
